#!/usr/bin/env sh

chmod -R a+rwx $(pwd)/.git
mkdir -p "$(pwd)/.git/hooks"

curl https://raw.githubusercontent.com/yabe-diverta/enforcing-convensional-commit/git-conventional-commits.json --output $(pwd)/git-conventional-commits.json
curl https://raw.githubusercontent.com/yabe-diverta/enforcing-convensional-commit/commit-msg --output $(pwd)/.git/hooks/commit-msg
